CategoryType.delete_all
CategoryType.create(id: 0, name: "location")
CategoryType.create(id: 2, name: "operator")
CategoryType.create(id: 3, name: "legal_or_person")
CategoryType.create(id: 4, name: "standard_service")
CategoryType.create(id: 5, name: "base_service")
CategoryType.create(id: 6, name: "service_direction")
CategoryType.create(id: 7, name: "param_value_type")
CategoryType.create(id: 8, name: "param_source")
CategoryType.create(id: 9, name: "unit")
CategoryType.create(id: 14, name: "comparison_operation")

CategoryLevel.delete_all
CategoryLevel.create(id: 2,type_id: 0, level: 2, name: "country")
CategoryLevel.create(id: 3,type_id: 0, level: 3, name: "region")
CategoryLevel.create(id: 20,type_id: 9, level: 0, name: "unit type")
CategoryLevel.create(id: 21,type_id: 9, level: 1, name: "unit")

Category.delete_all
Category.create(id: 1, type_id: 3, level_id: nil, parent_id: nil, name: "Legal")
Category.create(id: 2, type_id: 3, level_id: nil, parent_id: nil, name: "Person")

Category.create(id: 40, type_id: 4, level_id: nil, parent_id: nil, name: "Тариф")
Category.create(id: 41, type_id: 4, level_id: nil, parent_id: nil, name: "Роуминг")
Category.create(id: 42, type_id: 4, level_id: nil, parent_id: nil, name: "Специальная услуга")
Category.create(id: 43, type_id: 4, level_id: nil, parent_id: nil, name: "Опция тарифа")

Category.create(id: 50, type_id: 5, level_id: nil, parent_id: nil, name: "Звонок")
Category.create(id: 51, type_id: 5, level_id: nil, parent_id: nil, name: "СМС")
Category.create(id: 52, type_id: 5, level_id: nil, parent_id: nil, name: "ММС")
Category.create(id: 53, type_id: 5, level_id: nil, parent_id: nil, name: "2G")
Category.create(id: 54, type_id: 5, level_id: nil, parent_id: nil, name: "3G")
Category.create(id: 55, type_id: 5, level_id: nil, parent_id: nil, name: "4G")
Category.create(id: 56, type_id: 5, level_id: nil, parent_id: nil, name: "CDMA")
Category.create(id: 57, type_id: 5, level_id: nil, parent_id: nil, name: "WiFi")
Category.create(id: 58, type_id: 5, level_id: nil, parent_id: nil, name: "Подключение")
Category.create(id: 59, type_id: 5, level_id: nil, parent_id: nil, name: "Абонентская плата")
Category.create(id: 60, type_id: 5, level_id: nil, parent_id: nil, name: "Разовая плата")
Category.create(id: 61, type_id: 5, level_id: nil, parent_id: nil, name: "Прочее")
Category.create(id: 62, type_id: 5, level_id: nil, parent_id: nil, name: "Комбинация")

Category.create(id: 70, type_id: 6, level_id: nil, parent_id: nil, name: "Входящий")
Category.create(id: 71, type_id: 6, level_id: nil, parent_id: nil, name: "Исходящий")
Category.create(id: 72, type_id: 6, level_id: nil, parent_id: nil, name: "Без категории")

Category.create(id: 3, type_id: 7, level_id: nil, parent_id: nil, name: "boolean")
Category.create(id: 4, type_id: 7, level_id: nil, parent_id: nil, name: "integer")
Category.create(id: 5, type_id: 7, level_id: nil, parent_id: nil, name: "string")
Category.create(id: 6, type_id: 7, level_id: nil, parent_id: nil, name: "text")
Category.create(id: 7, type_id: 7, level_id: nil, parent_id: nil, name: "decimal")
Category.create(id: 8, type_id: 7, level_id: nil, parent_id: nil, name: "list")
Category.create(id: 9, type_id: 7, level_id: nil, parent_id: nil, name: "reference")
Category.create(id: 10, type_id: 7, level_id: nil, parent_id: nil, name: "datetime")

Category.create(id: 15, type_id: 8, level_id: nil, parent_id: nil, name: "User phones")
Category.create(id: 16, type_id: 8, level_id: nil, parent_id: nil, name: "User service description")
Category.create(id: 17, type_id: 8, level_id: nil, parent_id: nil, name: "Operator service description")
Category.create(id: 18, type_id: 8, level_id: nil, parent_id: nil, name: "Used service description")
Category.create(id: 19, type_id: 8, level_id: nil, parent_id: nil, name: "Tarif service description")

Category.create(id: 75,type_id: 9, level_id: 20, parent_id: nil, name: "characteristic_unit")
Category.create(id: 76,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_unit")
Category.create(id: 77,type_id: 9, level_id: 20, parent_id: nil, name: "cost_unit")
Category.create(id: 78,type_id: 9, level_id: 20, parent_id: nil, name: "date_time_unit")
Category.create(id: 79,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_speed_unit")

Category.create(id: 80, type_id: 9, level_id: 21, parent_id: 76, name: "Байт")
Category.create(id: 81, type_id: 9, level_id: 21, parent_id: 76, name: "Кб")
Category.create(id: 82, type_id: 9, level_id: 21, parent_id: 76, name: "Мб")
Category.create(id: 83, type_id: 9, level_id: 21, parent_id: 76, name: "Гб")

Category.create(id: 90, type_id: 9, level_id: 21, parent_id: 77, name: "RUR")
Category.create(id: 91, type_id: 9, level_id: 21, parent_id: 77, name: "USD")
Category.create(id: 92, type_id: 9, level_id: 21, parent_id: 77, name: "EUR")
Category.create(id: 93, type_id: 9, level_id: 21, parent_id: 77, name: "Grivna")
Category.create(id: 94, type_id: 9, level_id: 21, parent_id: 77, name: "GBP")

Category.create(id: 95, type_id: 9, level_id: 21, parent_id: 78, name: "секунда")
Category.create(id: 96, type_id: 9, level_id: 21, parent_id: 78, name: "минута")
Category.create(id: 97, type_id: 9, level_id: 21, parent_id: 78, name: "час")
Category.create(id: 98, type_id: 9, level_id: 21, parent_id: 78, name: "сутки")
Category.create(id: 99, type_id: 9, level_id: 21, parent_id: 78, name: "неделя")
Category.create(id: 100, type_id: 9, level_id: 21, parent_id: 78, name: "месяц")
Category.create(id: 101, type_id: 9, level_id: 21, parent_id: 78, name: "год")

Category.create(id: 110, type_id: 9, level_id: 21, parent_id: 79, name: "Кб/с")
Category.create(id: 111, type_id: 9, level_id: 21, parent_id: 79, name: "Мб/с")
Category.create(id: 112, type_id: 9, level_id: 21, parent_id: 79, name: "Гб/с")

Category.create(id: 120, type_id: 14, level_id: nil, parent_id: nil, name: "=")
Category.create(id: 121, type_id: 14, level_id: nil, parent_id: nil, name: "<>")
Category.create(id: 122, type_id: 14, level_id: nil, parent_id: nil, name: "<")
Category.create(id: 123, type_id: 14, level_id: nil, parent_id: nil, name: "<=")
Category.create(id: 124, type_id: 14, level_id: nil, parent_id: nil, name: ">")
Category.create(id: 125, type_id: 14, level_id: nil, parent_id: nil, name: "=>")


Category.create(id: 1020, type_id: 2, level_id: nil, parent_id: nil, name: "Djuice")
Category.create(id: 1021, type_id: 2, level_id: nil, parent_id: nil, name: "life:)")
Category.create(id: 1022, type_id: 2, level_id: nil, parent_id: nil, name: "PEOPLEnet")
Category.create(id: 1023, type_id: 2, level_id: nil, parent_id: nil, name: "TELE2")
Category.create(id: 1024, type_id: 2, level_id: nil, parent_id: nil, name: "Utel")
Category.create(id: 1025, type_id: 2, level_id: nil, parent_id: nil, name: "Билайн")
Category.create(id: 1026, type_id: 2, level_id: nil, parent_id: nil, name: "Енисейтелеком")
Category.create(id: 1027, type_id: 2, level_id: nil, parent_id: nil, name: "КиевСтар")
Category.create(id: 1028, type_id: 2, level_id: nil, parent_id: nil, name: "Мегафон")
Category.create(id: 1029, type_id: 2, level_id: nil, parent_id: nil, name: "Мотив")
Category.create(id: 1030, type_id: 2, level_id: nil, parent_id: nil, name: "МТС")
Category.create(id: 1031, type_id: 2, level_id: nil, parent_id: nil, name: "МТС-Украина")
Category.create(id: 1032, type_id: 2, level_id: nil, parent_id: nil, name: "Скайлинк")
Category.create(id: 1033, type_id: 2, level_id: nil, parent_id: nil, name: "СМАРТС")
Category.create(id: 1034, type_id: 2, level_id: nil, parent_id: nil, name: "Fixed line")

Category.create(id: 1100, type_id: 0, level_id: 2, parent_id: nil, name: "Россия")
Category.create(id: 1500, type_id: 0, level_id: 2, parent_id: nil, name: "Украина")

Category.create(id: 1101, type_id: 0, level_id: 3, parent_id: 1100, name: "Владимирская область")
Category.create(id: 1102, type_id: 0, level_id: 3, parent_id: 1100, name: "Волгоградская область")
Category.create(id: 1103, type_id: 0, level_id: 3, parent_id: 1100, name: "Ивановская область")
Category.create(id: 1104, type_id: 0, level_id: 3, parent_id: 1100, name: "Калининградская область")
Category.create(id: 1105, type_id: 0, level_id: 3, parent_id: 1100, name: "Калужская область")
Category.create(id: 1106, type_id: 0, level_id: 3, parent_id: 1100, name: "Кемеровская область")
Category.create(id: 1107, type_id: 0, level_id: 3, parent_id: 1100, name: "Краснодарский край")
Category.create(id: 1108, type_id: 0, level_id: 3, parent_id: 1100, name: "Красноярский край")
Category.create(id: 1109, type_id: 0, level_id: 3, parent_id: 1100, name: "Москва и Московская область")
Category.create(id: 1110, type_id: 0, level_id: 3, parent_id: 1100, name: "Нижегородская область")
Category.create(id: 1111, type_id: 0, level_id: 3, parent_id: 1100, name: "Новгородская область")
Category.create(id: 1112, type_id: 0, level_id: 3, parent_id: 1100, name: "Новосибирская область")
Category.create(id: 1113, type_id: 0, level_id: 3, parent_id: 1100, name: "Омская область")
Category.create(id: 1114, type_id: 0, level_id: 3, parent_id: 1100, name: "Пензенская область")
Category.create(id: 1115, type_id: 0, level_id: 3, parent_id: 1100, name: "Пермский край")
Category.create(id: 1116, type_id: 0, level_id: 3, parent_id: 1100, name: "Приморский край")
Category.create(id: 1117, type_id: 0, level_id: 3, parent_id: 1100, name: "Республика Башкортостан")
Category.create(id: 1118, type_id: 0, level_id: 3, parent_id: 1100, name: "Республика Саха (Якутия)")
Category.create(id: 1119, type_id: 0, level_id: 3, parent_id: 1100, name: "Республика Татарстан")
Category.create(id: 1120, type_id: 0, level_id: 3, parent_id: 1100, name: "Республика Удмуртия")
Category.create(id: 1121, type_id: 0, level_id: 3, parent_id: 1100, name: "Ростовская область")
Category.create(id: 1122, type_id: 0, level_id: 3, parent_id: 1100, name: "Самарская область")
Category.create(id: 1123, type_id: 0, level_id: 3, parent_id: 1100, name: "Санкт-Петербург / Ленинградская область")
Category.create(id: 1124, type_id: 0, level_id: 3, parent_id: 1100, name: "Саратовская область")
Category.create(id: 1125, type_id: 0, level_id: 3, parent_id: 1100, name: "Свердловская область / Екатеринбург")
Category.create(id: 1126, type_id: 0, level_id: 3, parent_id: 1100, name: "Ставропольский край")
Category.create(id: 1127, type_id: 0, level_id: 3, parent_id: 1100, name: "Тюменская область")
Category.create(id: 1128, type_id: 0, level_id: 3, parent_id: 1100, name: "Ульяновская область")
Category.create(id: 1129, type_id: 0, level_id: 3, parent_id: 1100, name: "Ханты-Мансийский АО")
Category.create(id: 1130, type_id: 0, level_id: 3, parent_id: 1100, name: "Челябинская область")
Category.create(id: 1131, type_id: 0, level_id: 3, parent_id: 1100, name: "Ямало-Ненецкий АО")
Category.create(id: 1132, type_id: 0, level_id: 3, parent_id: 1100, name: "Ярославская область")

Category.create(id: 1501, type_id: 0, level_id: 3, parent_id: 1500, name: "Украина")
