TarifClass.delete_all
#Билайн, частные, тарифы
TarifClass.create(id: 0  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Go!')
TarifClass.create(id: 1  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 1200')
TarifClass.create(id: 2  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 1450')
TarifClass.create(id: 3  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 2050')
TarifClass.create(id: 4  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 2070')
TarifClass.create(id: 5  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 300')
TarifClass.create(id: 6  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 3550')
TarifClass.create(id: 7  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Всё за 600')
TarifClass.create(id: 8  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Добро пожаловать')
TarifClass.create(id: 9  , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Мобильный пенсионер')
TarifClass.create(id: 10 , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Ноль сомнений')
TarifClass.create(id: 11 , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Первый детский')
TarifClass.create(id: 12 , operator_id: 1025, privacy_id: 2, standard_service_id: 40, name: 'Со-общение')
#Билайн, корпоративные, тарифы
TarifClass.create(id: 50 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Бизнес-партнеры')
TarifClass.create(id: 51 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Идеальный баланс')
TarifClass.create(id: 52 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Коллеги')
TarifClass.create(id: 53 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Общее дело')
TarifClass.create(id: 54 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Рабочая область')
TarifClass.create(id: 55 , operator_id: 1025, privacy_id: 1, standard_service_id: 40, name: 'Формула свободы')
#Мегафон, частные, тарифы
TarifClass.create(id: 100, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Вокруг света')
TarifClass.create(id: 101, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Все просто')
TarifClass.create(id: 102, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон все включено L')
TarifClass.create(id: 103, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон все включено L СИТИ')
TarifClass.create(id: 104, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон все включено M')
TarifClass.create(id: 105, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон все включено S')
TarifClass.create(id: 106, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон все включено VIP')
TarifClass.create(id: 107, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Мегафон онлайн')
TarifClass.create(id: 108, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Международный')
TarifClass.create(id: 109, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Переходи на ноль')
TarifClass.create(id: 110, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Подмосковный')
TarifClass.create(id: 111, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Подмосковный*')
TarifClass.create(id: 112, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Связь городов')
TarifClass.create(id: 113, operator_id: 1028, privacy_id: 2, standard_service_id: 40, name: 'Теплый прием')
#Мегафон, корпоративные, тарифы
TarifClass.create(id: 150, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Командировочный')
TarifClass.create(id: 151, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит М1000')
TarifClass.create(id: 152, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит М3000')
TarifClass.create(id: 153, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит М500')
TarifClass.create(id: 154, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит S1000')
TarifClass.create(id: 155, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит S3000')
TarifClass.create(id: 156, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный безлимит S500')
TarifClass.create(id: 157, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный стандарт')
TarifClass.create(id: 158, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Федеральный генеральный')
TarifClass.create(id: 159, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Федеральный особый')
TarifClass.create(id: 160, operator_id: 1028, privacy_id: 1, standard_service_id: 40, name: 'Федеральны универсальный')
#МТС, частные, тарифы
TarifClass.create(id: 200, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'RED Energy')
TarifClass.create(id: 201, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Smart')
TarifClass.create(id: 202, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Smart mini')
TarifClass.create(id: 203, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Smart+')
TarifClass.create(id: 204, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Ultra')
TarifClass.create(id: 205, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'МТС Коннект-4')
TarifClass.create(id: 206, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Проще простого')
TarifClass.create(id: 207, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Проще простого*')
TarifClass.create(id: 208, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Супер МТС')
TarifClass.create(id: 209, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Суперс МТС*')
TarifClass.create(id: 210, operator_id: 1030, privacy_id: 2, standard_service_id: 40, name: 'Твоя страна')
#МТС, корпоративные, тарифы
TarifClass.create(id: 250, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Бизнес безлимит L')
TarifClass.create(id: 251, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Бизнес безлимит XL')
TarifClass.create(id: 252, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Бизнес коннект')
TarifClass.create(id: 253, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Бизнес-общение')
TarifClass.create(id: 254, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Бизнес-сеть')
TarifClass.create(id: 255, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Единый бизнес безлимит')
TarifClass.create(id: 256, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Единый бизнес')
TarifClass.create(id: 257, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Корпоративный эксклюзив')
TarifClass.create(id: 258, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Областной бизнес')
TarifClass.create(id: 259, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Умный бизнес M')
TarifClass.create(id: 260, operator_id: 1030, privacy_id: 1, standard_service_id: 40, name: 'Умный бизнес S')
