CategoryType.delete_all
CategoryType.create(id: 0, name: "location")
CategoryType.create(id: 2, name: "operator")
CategoryType.create(id: 3, name: "legal_or_person")
CategoryType.create(id: 4, name: "standard_service")
CategoryType.create(id: 5, name: "base_service")
CategoryType.create(id: 6, name: "service_direction")
CategoryType.create(id: 7, name: "param_value_type")
CategoryType.create(id: 8, name: "param_source")
CategoryType.create(id: 9, name: "unit")
CategoryType.create(id: 14, name: "comparison_operator")
CategoryType.create(id: 15, name: "param_source_type")
CategoryType.create(id: 16, name: "field_display_type")
CategoryType.create(id: 17, name: "value_choose_option")
CategoryType.create(id: 18, name: "service_category_type")
CategoryType.create(id: 19, name: "operator_type")
CategoryType.create(id: 20, name: "user_service_status")
CategoryType.create(id: 21, name: "relation types")
CategoryType.create(id: 22, name: "phone usage patterns")
CategoryType.create(id: 23, name: "priority_type")
CategoryType.create(id: 24, name: "priority_relation")

CategoryLevel.delete_all
CategoryLevel.create(id: 0,type_id: 0, level: 0, name: "world")
CategoryLevel.create(id: 1,type_id: 0, level: 1, name: "continent")
CategoryLevel.create(id: 2,type_id: 0, level: 2, name: "country")
CategoryLevel.create(id: 3,type_id: 0, level: 3, name: "region")
CategoryLevel.create(id: 20,type_id: 9, level: 0, name: "unit type")
CategoryLevel.create(id: 21,type_id: 9, level: 1, name: "unit")

Category.delete_all
Category.create(id: 1, type_id: 3, level_id: nil, parent_id: nil, name: "Legal")
Category.create(id: 2, type_id: 3, level_id: nil, parent_id: nil, name: "Person")

Category.create(id: 40, type_id: 4, level_id: nil, parent_id: nil, name: "Тариф")
Category.create(id: 41, type_id: 4, level_id: nil, parent_id: nil, name: "Роуминг")
Category.create(id: 42, type_id: 4, level_id: nil, parent_id: nil, name: "Специальная услуга")
Category.create(id: 43, type_id: 4, level_id: nil, parent_id: nil, name: "Опция тарифа")

Category.create(id: 50, type_id: 5, level_id: nil, parent_id: nil, name: "Звонок")
Category.create(id: 51, type_id: 5, level_id: nil, parent_id: nil, name: "СМС")
Category.create(id: 52, type_id: 5, level_id: nil, parent_id: nil, name: "ММС")
Category.create(id: 53, type_id: 5, level_id: nil, parent_id: nil, name: "2G")
Category.create(id: 54, type_id: 5, level_id: nil, parent_id: nil, name: "3G")
Category.create(id: 55, type_id: 5, level_id: nil, parent_id: nil, name: "4G")
Category.create(id: 56, type_id: 5, level_id: nil, parent_id: nil, name: "CDMA")
Category.create(id: 57, type_id: 5, level_id: nil, parent_id: nil, name: "WiFi")
Category.create(id: 58, type_id: 5, level_id: nil, parent_id: nil, name: "periodic")
Category.create(id: 59, type_id: 5, level_id: nil, parent_id: nil, name: "one_time")

Category.create(id: 70, type_id: 6, level_id: nil, parent_id: nil, name: "Входящий")
Category.create(id: 71, type_id: 6, level_id: nil, parent_id: nil, name: "Исходящий")
Category.create(id: 72, type_id: 6, level_id: nil, parent_id: nil, name: "Без категории")

Category.create(id: 3, type_id: 7, level_id: nil, parent_id: nil, name: "boolean")
Category.create(id: 4, type_id: 7, level_id: nil, parent_id: nil, name: "integer")
Category.create(id: 5, type_id: 7, level_id: nil, parent_id: nil, name: "string")
Category.create(id: 6, type_id: 7, level_id: nil, parent_id: nil, name: "text")
Category.create(id: 7, type_id: 7, level_id: nil, parent_id: nil, name: "decimal")
Category.create(id: 8, type_id: 7, level_id: nil, parent_id: nil, name: "list")
Category.create(id: 9, type_id: 7, level_id: nil, parent_id: nil, name: "reference")
Category.create(id: 10, type_id: 7, level_id: nil, parent_id: nil, name: "datetime")
Category.create(id: 11, type_id: 7, level_id: nil, parent_id: nil, name: "json")
Category.create(id: 12, type_id: 7, level_id: nil, parent_id: nil, name: "array")

Category.create(id: 15, type_id: 8, level_id: nil, parent_id: nil, name: "User phones")
Category.create(id: 16, type_id: 8, level_id: nil, parent_id: nil, name: "User service description")
Category.create(id: 17, type_id: 8, level_id: nil, parent_id: nil, name: "Operator service description")
Category.create(id: 18, type_id: 8, level_id: nil, parent_id: nil, name: "Used service description")
Category.create(id: 19, type_id: 8, level_id: nil, parent_id: nil, name: "Tarif service description")

Category.create(id: 75,type_id: 9, level_id: 20, parent_id: nil, name: "characteristic_unit")
Category.create(id: 76,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_unit")
Category.create(id: 77,type_id: 9, level_id: 20, parent_id: nil, name: "cost_unit")
Category.create(id: 78,type_id: 9, level_id: 20, parent_id: nil, name: "date_time_unit")
Category.create(id: 79,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_speed_unit")

Category.create(id: 80, type_id: 9, level_id: 21, parent_id: 76, name: "Байт")
Category.create(id: 81, type_id: 9, level_id: 21, parent_id: 76, name: "Кб")
Category.create(id: 82, type_id: 9, level_id: 21, parent_id: 76, name: "Мб")
Category.create(id: 83, type_id: 9, level_id: 21, parent_id: 76, name: "Гб")

Category.create(id: 90, type_id: 9, level_id: 21, parent_id: 77, name: "RUR")
Category.create(id: 91, type_id: 9, level_id: 21, parent_id: 77, name: "USD")
Category.create(id: 92, type_id: 9, level_id: 21, parent_id: 77, name: "EUR")
Category.create(id: 93, type_id: 9, level_id: 21, parent_id: 77, name: "Grivna")
Category.create(id: 94, type_id: 9, level_id: 21, parent_id: 77, name: "GBP")

Category.create(id: 95, type_id: 9, level_id: 21, parent_id: 78, name: "секунда")
Category.create(id: 96, type_id: 9, level_id: 21, parent_id: 78, name: "минута")
Category.create(id: 97, type_id: 9, level_id: 21, parent_id: 78, name: "час")
Category.create(id: 98, type_id: 9, level_id: 21, parent_id: 78, name: "сутки")
Category.create(id: 99, type_id: 9, level_id: 21, parent_id: 78, name: "неделя")
Category.create(id: 100, type_id: 9, level_id: 21, parent_id: 78, name: "месяц")
Category.create(id: 101, type_id: 9, level_id: 21, parent_id: 78, name: "год")

Category.create(id: 110, type_id: 9, level_id: 21, parent_id: 79, name: "Кб/с")
Category.create(id: 111, type_id: 9, level_id: 21, parent_id: 79, name: "Мб/с")
Category.create(id: 112, type_id: 9, level_id: 21, parent_id: 79, name: "Гб/с")

Category.create(id: 115, type_id: 9, level_id: 21, parent_id: 75, name: "шт.")

Category.create(id: 120, type_id: 14, level_id: nil, parent_id: nil, name: "=")
Category.create(id: 121, type_id: 14, level_id: nil, parent_id: nil, name: "!=")
Category.create(id: 122, type_id: 14, level_id: nil, parent_id: nil, name: "<")
Category.create(id: 123, type_id: 14, level_id: nil, parent_id: nil, name: "<=")
Category.create(id: 124, type_id: 14, level_id: nil, parent_id: nil, name: ">")
Category.create(id: 125, type_id: 14, level_id: nil, parent_id: nil, name: "=>")
Category.create(id: 126, type_id: 14, level_id: nil, parent_id: nil, name: "in")
Category.create(id: 127, type_id: 14, level_id: nil, parent_id: nil, name: "not_in")

Category.create(id: 130, type_id: 15, level_id: nil, parent_id: nil, name: "original")
Category.create(id: 131, type_id: 15, level_id: nil, parent_id: nil, name: "intermediate")
Category.create(id: 132, type_id: 15, level_id: nil, parent_id: nil, name: "input")

Category.create(id: 135, type_id: 16, level_id: nil, parent_id: nil, name: "value")
Category.create(id: 136, type_id: 16, level_id: nil, parent_id: nil, name: "list")
Category.create(id: 137, type_id: 16, level_id: nil, parent_id: nil, name: "table")
Category.create(id: 138, type_id: 16, level_id: nil, parent_id: nil, name: "string")
Category.create(id: 139, type_id: 16, level_id: nil, parent_id: nil, name: "query")

Category.create(id: 150, type_id: 17, level_id: nil, parent_id: nil, name: "field")
Category.create(id: 151, type_id: 17, level_id: nil, parent_id: nil, name: "single_value")
Category.create(id: 152, type_id: 17, level_id: nil, parent_id: nil, name: "multiple_value")
Category.create(id: 153, type_id: 17, level_id: nil, parent_id: nil, name: "value_param_is_criterium_param")

Category.create(id: 160, type_id: 18, level_id: nil, parent_id: nil, name: "common")
Category.create(id: 161, type_id: 18, level_id: nil, parent_id: nil, name: "specific")

Category.create(id: 170, type_id: 19, level_id: nil, parent_id: nil, name: "mobile")
Category.create(id: 171, type_id: 19, level_id: nil, parent_id: nil, name: "fixed line")

Category.create(id: 175, type_id: 20, level_id: nil, parent_id: nil, name: "subscribed")
Category.create(id: 176, type_id: 20, level_id: nil, parent_id: nil, name: "unsubscribed")
Category.create(id: 177, type_id: 20, level_id: nil, parent_id: nil, name: "expired")

Category.create(id: 190, type_id: 21, level_id: nil, parent_id: nil, name: "home regions")
Category.create(id: 191, type_id: 21, level_id: nil, parent_id: nil, name: "operator country groups")
Category.create(id: 192, type_id: 21, level_id: nil, parent_id: nil, name: "main operator by country")

Category.create(id: 200, type_id: 22, level_id: nil, parent_id: nil, name: "in own regions")
Category.create(id: 201, type_id: 22, level_id: nil, parent_id: 200, name: "active user of calls")
Category.create(id: 202, type_id: 22, level_id: nil, parent_id: 200, name: "active user of sms")
Category.create(id: 203, type_id: 22, level_id: nil, parent_id: 200, name: "active user of internet")

Category.create(id: 210, type_id: 22, level_id: nil, parent_id: nil, name: "in home regions")
Category.create(id: 211, type_id: 22, level_id: nil, parent_id: 210, name: "active user of calls")
Category.create(id: 212, type_id: 22, level_id: nil, parent_id: 210, name: "active user of sms")
Category.create(id: 213, type_id: 22, level_id: nil, parent_id: 210, name: "active user of internet")
Category.create(id: 214, type_id: 22, level_id: nil, parent_id: 210, name: "no home region activity")

Category.create(id: 220, type_id: 22, level_id: nil, parent_id: nil, name: "in own country")
Category.create(id: 221, type_id: 22, level_id: nil, parent_id: 220, name: "active user of calls")
Category.create(id: 222, type_id: 22, level_id: nil, parent_id: 220, name: "active user of sms")
Category.create(id: 223, type_id: 22, level_id: nil, parent_id: 220, name: "active user of internet")
Category.create(id: 224, type_id: 22, level_id: nil, parent_id: 220, name: "no own country activity")

Category.create(id: 230, type_id: 22, level_id: nil, parent_id: nil, name: "abroad")
Category.create(id: 231, type_id: 22, level_id: nil, parent_id: 230, name: "active user of calls")
Category.create(id: 232, type_id: 22, level_id: nil, parent_id: 230, name: "active user of sms")
Category.create(id: 233, type_id: 22, level_id: nil, parent_id: 230, name: "active user of internet")
Category.create(id: 234, type_id: 22, level_id: nil, parent_id: 230, name: "no abroad activity")

Category.create(id: 300, type_id: 23, level_id: nil, parent_id: nil, name: "general priority")
Category.create(id: 301, type_id: 23, level_id: nil, parent_id: nil, name: "individual priority")
Category.create(id: 302, type_id: 23, level_id: nil, parent_id: nil, name: "dependent is required for main")
Category.create(id: 303, type_id: 23, level_id: nil, parent_id: nil, name: "main is incompatible with dependent")

Category.create(id: 310, type_id: 24, level_id: nil, parent_id: nil, name: "main has higher priority")
Category.create(id: 311, type_id: 24, level_id: nil, parent_id: nil, name: "main has lower priority")

Category.create(id: _russian_operators, type_id: 2, level_id: nil, parent_id: nil, name: "Russian operators")
Category.create(id: _foreign_operators, type_id: 2, level_id: nil, parent_id: nil, name: "Foreign operators")
Category.create(id: 1020, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Djuice")
Category.create(id: 1021, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "life:)")
Category.create(id: 1022, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "PEOPLEnet")
Category.create(id: 1023, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "TELE2")
Category.create(id: 1024, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Utel")
Category.create(id: _beeline, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Билайн")
Category.create(id: 1026, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Енисейтелеком")
Category.create(id: 1027, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "КиевСтар")
Category.create(id: _megafon, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Мегафон")
Category.create(id: 1029, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Мотив")
Category.create(id: _mts, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "МТС")
Category.create(id: _mts_ukrain, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "МТС-Украина")
Category.create(id: 1032, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Скайлинк")
Category.create(id: 1033, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "СМАРТС")
Category.create(id: _fixed_line_operator, type_id: 2, level_id: nil, parent_id: _russian_operators, name: "Ростелеком Fixed line")
Category.create(id: _operator_great_britain, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_great_britain")
Category.create(id: _operator_germany, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_germany")
Category.create(id: _operator_france, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_france")
Category.create(id: _operator_spain, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_spain")
Category.create(id: _operator_poland, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_poland")
Category.create(id: _operator_holand, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_holand")
Category.create(id: _operator_china, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_china")
Category.create(id: _operator_india, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_india")
Category.create(id: _operator_turkey, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_turkey")
Category.create(id: _operator_abhazia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_abhazia")
Category.create(id: _operator_azerbaigan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_azerbaigan")
Category.create(id: _operator_armenia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_armenia")
Category.create(id: _operator_gruzia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_gruzia")
Category.create(id: _operator_usa, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_usa")
Category.create(id: _operator_canada, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_canada")
Category.create(id: _operator_mexica, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_mexica")
Category.create(id: _operator_cuba, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_cuba")
Category.create(id: _operator_yamayka, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_yamayka")
Category.create(id: _operator_brasilia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_brasilia")
Category.create(id: _operator_argentina, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_argentina")
Category.create(id: _operator_chily, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_chily")
Category.create(id: _operator_bolivia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_bolivia")
Category.create(id: _operator_egypt, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_egypt")
Category.create(id: _operator_uae, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_uae")
Category.create(id: _operator_south_africa, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_south_africa")
Category.create(id: _operator_livia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_livia")

Category.create(id: _operator_kazakhstan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_kazakhstan")
Category.create(id: _operator_kyrgyzstan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_kyrgyzstan")
Category.create(id: _operator_tajikistan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_tajikistan")
Category.create(id: _operator_turkmenistan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_turkmenistan")
Category.create(id: _operator_uzbekistan, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_uzbekistan")
Category.create(id: _operator_south_ossetia, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_south_ossetia")
Category.create(id: _operator_belarus, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "operator_belarus")
Category.create(id: _operator_moldova, type_id: 2, level_id: nil, parent_id: _foreign_operators, name: "_operator_moldova")

Category.create(id: 1101, type_id: 0, level_id: 3, parent_id: _russia, name: "Владимирская область")
Category.create(id: 1102, type_id: 0, level_id: 3, parent_id: _russia, name: "Волгоградская область")
Category.create(id: 1103, type_id: 0, level_id: 3, parent_id: _russia, name: "Ивановская область")
Category.create(id: 1104, type_id: 0, level_id: 3, parent_id: _russia, name: "Калининградская область")
Category.create(id: 1105, type_id: 0, level_id: 3, parent_id: _russia, name: "Калужская область")
Category.create(id: 1106, type_id: 0, level_id: 3, parent_id: _russia, name: "Кемеровская область")
Category.create(id: 1107, type_id: 0, level_id: 3, parent_id: _russia, name: "Краснодарский край")
Category.create(id: 1108, type_id: 0, level_id: 3, parent_id: _russia, name: "Красноярский край")
Category.create(id: 1109, type_id: 0, level_id: 3, parent_id: _russia, name: "Московская область")
Category.create(id: 1110, type_id: 0, level_id: 3, parent_id: _russia, name: "Нижегородская область")
Category.create(id: 1111, type_id: 0, level_id: 3, parent_id: _russia, name: "Новгородская область")
Category.create(id: 1112, type_id: 0, level_id: 3, parent_id: _russia, name: "Новосибирская область")
Category.create(id: 1113, type_id: 0, level_id: 3, parent_id: _russia, name: "Омская область")
Category.create(id: 1114, type_id: 0, level_id: 3, parent_id: _russia, name: "Пензенская область")
Category.create(id: 1115, type_id: 0, level_id: 3, parent_id: _russia, name: "Пермский край")
Category.create(id: 1116, type_id: 0, level_id: 3, parent_id: _russia, name: "Приморский край")
Category.create(id: 1117, type_id: 0, level_id: 3, parent_id: _russia, name: "Республика Башкортостан")
Category.create(id: 1118, type_id: 0, level_id: 3, parent_id: _russia, name: "Республика Саха (Якутия)")
Category.create(id: 1119, type_id: 0, level_id: 3, parent_id: _russia, name: "Республика Татарстан")
Category.create(id: 1120, type_id: 0, level_id: 3, parent_id: _russia, name: "Республика Удмуртия")
Category.create(id: 1121, type_id: 0, level_id: 3, parent_id: _russia, name: "Ростовская область")
Category.create(id: 1122, type_id: 0, level_id: 3, parent_id: _russia, name: "Самарская область")
Category.create(id: 1123, type_id: 0, level_id: 3, parent_id: _russia, name: "Ленинградская область")
Category.create(id: 1124, type_id: 0, level_id: 3, parent_id: _russia, name: "Саратовская область")
Category.create(id: 1125, type_id: 0, level_id: 3, parent_id: _russia, name: "Свердловская область")
Category.create(id: 1126, type_id: 0, level_id: 3, parent_id: _russia, name: "Ставропольский край")
Category.create(id: 1127, type_id: 0, level_id: 3, parent_id: _russia, name: "Тюменская область")
Category.create(id: 1128, type_id: 0, level_id: 3, parent_id: _russia, name: "Ульяновская область")
Category.create(id: 1129, type_id: 0, level_id: 3, parent_id: _russia, name: "Ханты-Мансийский АО")
Category.create(id: 1130, type_id: 0, level_id: 3, parent_id: _russia, name: "Челябинская область")
Category.create(id: 1131, type_id: 0, level_id: 3, parent_id: _russia, name: "Ямало-Ненецкий АО")
Category.create(id: 1132, type_id: 0, level_id: 3, parent_id: _russia, name: "Ярославская область")
Category.create(id: 1133, type_id: 0, level_id: 3, parent_id: _russia, name: "Москва")
Category.create(id: 1134, type_id: 0, level_id: 3, parent_id: _russia, name: "Санкт-Петербург")
Category.create(id: 1135, type_id: 0, level_id: 3, parent_id: _russia, name: "Екатеринбург")

Category.create(id: 1501, type_id: 0, level_id: 3, parent_id: _ukraiun, name: "Украина")

Category.create(id: _world, type_id: 0, level_id: 0, parent_id: nil, name: "World")

Category.create(id: _europe, type_id: 0, level_id: 1, parent_id: _world, name: "Europe")
Category.create(id: _asia, type_id: 0, level_id: 1, parent_id: _world, name: "Asia")
Category.create(id: _noth_america, type_id: 0, level_id: 1, parent_id: _world, name: "Noth America")
Category.create(id: _south_america, type_id: 0, level_id: 1, parent_id: _world, name: "South America")
Category.create(id: _africa, type_id: 0, level_id: 1, parent_id: _world, name: "Africa")

Category.create(id: _austria, type_id: 0, level_id: 2, parent_id: _europe, name: "Austria")
Category.create(id: _albania, type_id: 0, level_id: 2, parent_id: _europe, name: "Albania")
Category.create(id: _andorra, type_id: 0, level_id: 2, parent_id: _europe, name: "Andorra")
Category.create(id: _belgium, type_id: 0, level_id: 2, parent_id: _europe, name: "Belgium")
Category.create(id: _bulgaria, type_id: 0, level_id: 2, parent_id: _europe, name: "Bulgaria")
Category.create(id: _bosnia_and_herzegovina, type_id: 0, level_id: 2, parent_id: _europe, name: "Bosnia and Herzegovina")
Category.create(id: _vatican, type_id: 0, level_id: 2, parent_id: _europe, name: "The Vatican")
Category.create(id: _great_britain, type_id: 0, level_id: 2, parent_id: _europe, name: "Great Britain")
Category.create(id: _hungary, type_id: 0, level_id: 2, parent_id: _europe, name: "Hungary")
Category.create(id: _germany, type_id: 0, level_id: 2, parent_id: _europe, name: "Germany")
Category.create(id: _gibraltar, type_id: 0, level_id: 2, parent_id: _europe, name: "Gibraltar")
Category.create(id: _greenland, type_id: 0, level_id: 2, parent_id: _europe, name: "Greenland")
Category.create(id: _denmark, type_id: 0, level_id: 2, parent_id: _europe, name: "Denmark")
Category.create(id: _greece, type_id: 0, level_id: 2, parent_id: _europe, name: "Greece")
Category.create(id: _ireland, type_id: 0, level_id: 2, parent_id: _europe, name: "Ireland")
Category.create(id: _israel, type_id: 0, level_id: 2, parent_id: _europe, name: "Israel")
Category.create(id: _iceland, type_id: 0, level_id: 2, parent_id: _europe, name: "Iceland")
Category.create(id: _spain, type_id: 0, level_id: 2, parent_id: _europe, name: "Spain")
Category.create(id: _italy, type_id: 0, level_id: 2, parent_id: _europe, name: "Italy")
Category.create(id: _cyprus, type_id: 0, level_id: 2, parent_id: _europe, name: "Cyprus")
Category.create(id: _latvia, type_id: 0, level_id: 2, parent_id: _europe, name: "Latvia")
Category.create(id: _liechtenstein, type_id: 0, level_id: 2, parent_id: _europe, name: "Liechtenstein")
Category.create(id: _lithuania, type_id: 0, level_id: 2, parent_id: _europe, name: "Lithuania")
Category.create(id: _luxembourg, type_id: 0, level_id: 2, parent_id: _europe, name: "Luxembourg")
Category.create(id: _macedonia, type_id: 0, level_id: 2, parent_id: _europe, name: "Macedonia")
Category.create(id: _malta, type_id: 0, level_id: 2, parent_id: _europe, name: "Malta")
Category.create(id: _monaco, type_id: 0, level_id: 2, parent_id: _europe, name: "Monaco")
Category.create(id: _netherlands, type_id: 0, level_id: 2, parent_id: _europe, name: "Netherlands")
Category.create(id: _norway, type_id: 0, level_id: 2, parent_id: _europe, name: "Norway")
Category.create(id: _poland, type_id: 0, level_id: 2, parent_id: _europe, name: "Poland")
Category.create(id: _portugal, type_id: 0, level_id: 2, parent_id: _europe, name: "Portugal")
Category.create(id: _romania, type_id: 0, level_id: 2, parent_id: _europe, name: "Romania")
Category.create(id: _san_marino, type_id: 0, level_id: 2, parent_id: _europe, name: "San Marino")
Category.create(id: _serbia, type_id: 0, level_id: 2, parent_id: _europe, name: "Serbia")
Category.create(id: _slovakia, type_id: 0, level_id: 2, parent_id: _europe, name: "Slovakia")
Category.create(id: _slovenia, type_id: 0, level_id: 2, parent_id: _europe, name: "Slovenia")
Category.create(id: _turkey, type_id: 0, level_id: 2, parent_id: _europe, name: "Turkey")
Category.create(id: _the_faroe_islands, type_id: 0, level_id: 2, parent_id: _europe, name: "the Faroe Islands")
Category.create(id: _finland, type_id: 0, level_id: 2, parent_id: _europe, name: "Finland")
Category.create(id: _france, type_id: 0, level_id: 2, parent_id: _europe, name: "France")
Category.create(id: _croatia, type_id: 0, level_id: 2, parent_id: _europe, name: "Croatia")
Category.create(id: _montenegro, type_id: 0, level_id: 2, parent_id: _europe, name: "Montenegro")
Category.create(id: _czech_republic, type_id: 0, level_id: 2, parent_id: _europe, name: "Czech Republic")
Category.create(id: _switzerland, type_id: 0, level_id: 2, parent_id: _europe, name: "Switzerland")
Category.create(id: _sweden, type_id: 0, level_id: 2, parent_id: _europe, name: "Sweden")
Category.create(id: _estonia, type_id: 0, level_id: 2, parent_id: _europe, name: "Estonia")

Category.create(id: _belarus, type_id: 0, level_id: 2, parent_id: _europe, name: "Belarus")
Category.create(id: _moldova, type_id: 0, level_id: 2, parent_id: _europe, name: "Moldova")
Category.create(id: _ukraiun, type_id: 0, level_id: 2, parent_id: _europe, name: "Ukraine")
Category.create(id: _russia, type_id: 0, level_id: 2, parent_id: _europe, name: "Russia")

Category.create(id: _china, type_id: 0, level_id: 2, parent_id: _asia, name: "China")
Category.create(id: _india, type_id: 0, level_id: 2, parent_id: _asia, name: "India")
Category.create(id: _abkhazia, type_id: 0, level_id: 2, parent_id: _asia, name: "Abkhazia")
Category.create(id: _armenia, type_id: 0, level_id: 2, parent_id: _asia, name: "Armenia")
Category.create(id: _azerbaijan, type_id: 0, level_id: 2, parent_id: _asia, name: "Azerbaijan")
Category.create(id: _georgia, type_id: 0, level_id: 2, parent_id: _asia, name: "Georgia")
Category.create(id: _kazakhstan, type_id: 0, level_id: 2, parent_id: _asia, name: "Kazakhstan")
Category.create(id: _kyrgyzstan, type_id: 0, level_id: 2, parent_id: _asia, name: "Kyrgyzstan")
Category.create(id: _tajikistan, type_id: 0, level_id: 2, parent_id: _asia, name: "Tajikistan")
Category.create(id: _turkmenistan, type_id: 0, level_id: 2, parent_id: _asia, name: "Turkmenistan")
Category.create(id: _uzbekistan, type_id: 0, level_id: 2, parent_id: _asia, name: "Uzbekistan")
Category.create(id: _south_ossetia, type_id: 0, level_id: 2, parent_id: _asia, name: "South Ossetia")

Category.create(id: _usa, type_id: 0, level_id: 2, parent_id: _noth_america, name: "USA")
Category.create(id: _canada, type_id: 0, level_id: 2, parent_id: _noth_america, name: "Canada")
Category.create(id: _mexica, type_id: 0, level_id: 2, parent_id: _noth_america, name: "Mexica")
Category.create(id: _cuba, type_id: 0, level_id: 2, parent_id: _noth_america, name: "Cuba")
Category.create(id: _yamayka, type_id: 0, level_id: 2, parent_id: _noth_america, name: "Yamayka")

Category.create(id: _brasilia, type_id: 0, level_id: 2, parent_id: _south_america, name: "Brasilia")
Category.create(id: _argentina, type_id: 0, level_id: 2, parent_id: _south_america, name: "Argentina")
Category.create(id: _chily, type_id: 0, level_id: 2, parent_id: _south_america, name: "Chily")
Category.create(id: _bolivia, type_id: 0, level_id: 2, parent_id: _south_america, name: "Bolivia")

Category.create(id: _egypt, type_id: 0, level_id: 2, parent_id: _africa, name: "Egypt")
Category.create(id: _uae, type_id: 0, level_id: 2, parent_id: _africa, name: "UAE")
Category.create(id: _south_africa, type_id: 0, level_id: 2, parent_id: _africa, name: "South Africa")
Category.create(id: _livia, type_id: 0, level_id: 2, parent_id: _africa, name: "Livia")
